### ISSUE TITLE
Catalog needs an update.

### ISSUE THREAD

**Issue by abhnil** [joshuatorrance/barpa-barra2-amos2024#2]
The BARRA2 data has been updated, but the old catalog has old paths set. This requires an update for some recently updated variables.

**Comment by joshuatorrance** [comment]
Hi @abhnil,

Thanks for pointing this out! As you said, the Intake catalogues for BARRA2 were out-of-date due to some updates we made to the paths on Gadi.

The NCI team have updated the catalogue for us and these notebooks seem to be working again!

Kind regards,
Josh
